name: CI

on:
  push:
    branches:
      - '**'
    workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: abc123123
          POSTGRES_DB: banking_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: go set up
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build_version
          retention-days: 1

  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download artifact
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

  deploy_stag:
    runs-on: ubuntu-latest
    needs: [deploy_dev]
    if: github.ref == 'refs/heads/dev'
    environment:
      name: stg
    steps:
      - name: Download artifact
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
